language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  
before_script:
  - cp config/travis-ci.conf.php-dist config/test.conf.php
  - ln -s ${TRAVIS_BUILD_DIR}/public/themes/bootstrap/test test/themes/bootstrap

script: phpunit --bootstrap test/bootstrap.php --colors .
